### ISSUE TITLE
Header do site

### ISSUE THREAD

**Issue by carlosreiker** [gt-05/grupo-04#1]
Criar header do site com menu centralizado ao meio

Itens do menu

- Home
- Ao clicar deve direcionar para o arquivo index.html
- Calcular frete
 Ao clicar deve direcionar para o arquivo calcular-frete.html
- Contato
- Ao clicar deve direcionar para o arquivo contato.html

**Comment by Maybonat** [comment]
https://design.penpot.app/#/view/f5fe9278-89db-81e9-8004-f99f7807c6c6?page-id=f5fe9278-89db-81e9-8004-f99f7807c6c7&section=interactions&index=0&share-id=1ab1fa36-da8e-809d-8004-f9a04a0db1db
